# Generated by Django 4.1.6 on 2023-04-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_based_app', '0004_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
